on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Analyze quaternion code with Pylint
        run: |
          pylint $(git ls-files '*.py') --disable=C0116,E0213,E1102,R0902,R0904 --exit-zero
  